FROM node:8.14-alpine
LABEL mantainer="egormaksimchuk@gmail.com"

WORKDIR /usr/src/app
ENV MONGODB_URL="mongodb://admin:admin@geography-db:27017/geographydb?authSource=admin"

COPY package.json /usr/src/app
RUN npm install
COPY . .

EXPOSE 4000
CMD ["node", "app.js"]
